// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Adr {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  decision_status: "proposed" | "accepted" | "deprecated" | "superseded";
  problem: PortableTextBlock[];
  decision: PortableTextBlock[];
  alternatives?: PortableTextBlock[];
  consequences?: PortableTextBlock[];
  author?: string;
  date: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content: PortableTextBlock[];
  author?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Incident {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  severity: "sev1" | "sev2" | "sev3" | "sev4";
  incident_status: "investigating" | "monitoring" | "resolved";
  date: string;
  summary: string;
  root_cause?: PortableTextBlock[];
  resolution?: PortableTextBlock[];
  lessons_learned?: PortableTextBlock[];
  author?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    adrs: Adr;
    articles: Article;
    incidents: Incident;
  }
}